// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAKCjnmg0EExehB2RiDGnuSNxgmQO7Xzk',
    appId: '1:78296788599:web:40911fd625e47f9f39e072',
    messagingSenderId: '78296788599',
    projectId: 'sing-up-5229b',
    authDomain: 'sing-up-5229b.firebaseapp.com',
    storageBucket: 'sing-up-5229b.appspot.com',
    measurementId: 'G-1FV14LQ0P8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCHlstyDe-_Zdo_9EgOp0pOaA_NoT9SB34',
    appId: '1:78296788599:android:e66ec41ef329022e39e072',
    messagingSenderId: '78296788599',
    projectId: 'sing-up-5229b',
    storageBucket: 'sing-up-5229b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqe5LHBvq-L8py2rYn7bBPjJ4f5EUsRUI',
    appId: '1:78296788599:ios:33b210f0b1ab685039e072',
    messagingSenderId: '78296788599',
    projectId: 'sing-up-5229b',
    storageBucket: 'sing-up-5229b.appspot.com',
    iosBundleId: 'com.example.modul8app1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAqe5LHBvq-L8py2rYn7bBPjJ4f5EUsRUI',
    appId: '1:78296788599:ios:33b210f0b1ab685039e072',
    messagingSenderId: '78296788599',
    projectId: 'sing-up-5229b',
    storageBucket: 'sing-up-5229b.appspot.com',
    iosBundleId: 'com.example.modul8app1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAKCjnmg0EExehB2RiDGnuSNxgmQO7Xzk',
    appId: '1:78296788599:web:cc0037fa1b1b8d9c39e072',
    messagingSenderId: '78296788599',
    projectId: 'sing-up-5229b',
    authDomain: 'sing-up-5229b.firebaseapp.com',
    storageBucket: 'sing-up-5229b.appspot.com',
    measurementId: 'G-74DWMC71YE',
  );
}
